# -*- coding: utf-8 -*-
"""Watershed Segmentation Algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GM7nz9CgZ0SgQQ18KbKalgrDCVX42VCy
"""

# 1. Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Imports
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from skimage.segmentation import watershed
from skimage.feature import peak_local_max, local_binary_pattern
from scipy import ndimage
import xml.etree.ElementTree as ET

# 3. Paths
image_dir = '/content/drive/MyDrive/train'  # Input images
output_dir = '/content/drive/MyDrive/wsaresults'  # Output images
xml_dir = '/content/drive/MyDrive/annotation'  # Ground truth annotations
os.makedirs(output_dir, exist_ok=True)

# 4. Initialize total count and result dictionary
total_tree_count = 0
result_dict = {}

# 5. Parse VOC XML Annotations
def parse_voc_annotations_easy(xml_dir):
    annotations = {}
    for filename in os.listdir(xml_dir):
        if not filename.endswith('.xml'):
            continue
        xml_path = os.path.join(xml_dir, filename)
        tree = ET.parse(xml_path)
        root = tree.getroot()
        image_filename = root.find('filename').text
        boxes = []
        for obj in root.findall('object'):
            bbox = obj.find('bndbox')
            xmin = int(bbox.find('xmin').text)
            ymin = int(bbox.find('ymin').text)
            xmax = int(bbox.find('xmax').text)
            ymax = int(bbox.find('ymax').text)
            boxes.append((xmin, ymin, xmax, ymax))
        annotations[image_filename] = boxes
    return annotations

ground_truth = parse_voc_annotations_easy(xml_dir)
print(list(ground_truth.items())[:3])  # Sample output

# 6. Green mask function
def apply_green_mask(image):
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    lower_green = np.array([35, 40, 40])
    upper_green = np.array([90, 255, 255])
    mask = cv2.inRange(hsv, lower_green, upper_green)
    result = cv2.bitwise_and(image, image, mask=mask)
    return result, mask

# 7. LBP helper for texture filtering
def compute_lbp_hist(gray_roi):
    radius = 1
    n_points = 8 * radius
    lbp = local_binary_pattern(gray_roi, n_points, radius, method="uniform")
    hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, n_points + 3), range=(0, n_points + 2), density=True)
    return hist

# 8. Main segmentation function
def watershed_segmentation(image_path):
    global total_tree_count
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Could not load {image_path}")
        return

    masked_image, green_mask = apply_green_mask(image)
    gray = cv2.cvtColor(masked_image, cv2.COLOR_BGR2GRAY)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    enhanced = clahe.apply(gray)
    blurred = cv2.GaussianBlur(enhanced, (5, 5), 0)
    _, binary = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    kernel = np.ones((5, 5), np.uint8)
    closed = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel, iterations=3)
    D = ndimage.distance_transform_edt(closed)
    localMax = peak_local_max(D, labels=closed, min_distance=60, exclude_border=False)

    markers = np.zeros_like(D, dtype=np.int32)
    for idx, point in enumerate(localMax):
        markers[point[0], point[1]] = idx + 1

    labels = watershed(-D, markers, mask=closed)
    num_trees = 0
    bounding_boxes = []

    for label in np.unique(labels):
        if label == 0:
            continue
        mask = (labels == label).astype(np.uint8) * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in contours:
            x, y, w, h = cv2.boundingRect(cnt)
            roi = gray[y:y+h, x:x+w]
            if roi.shape[0] < 10 or roi.shape[1] < 10:
                continue

            hist = compute_lbp_hist(roi)
            uniform_score = hist[0]
            if uniform_score > 0.6:
                continue

            bounding_boxes.append((x, y, x + w, y + h))
            num_trees += 1

    total_tree_count += num_trees
    print(f"{os.path.basename(image_path)} - {num_trees}")

    filename = os.path.basename(image_path)
    result_dict[filename] = bounding_boxes

    result_image = image.copy()
    for box in bounding_boxes:
        x1, y1, x2, y2 = box
        cv2.rectangle(result_image, (x1, y1), (x2, y2), (0, 255, 0), 2)

    cv2.putText(result_image, f"{num_trees}", (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.2, (0, 0, 255), 3)
    save_path = os.path.join(output_dir, f"result_{filename}")
    cv2.imwrite(save_path, result_image)

# 9. Run segmentation
image_files = [f for f in os.listdir(image_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tiff'))]
for img_file in image_files:
    img_path = os.path.join(image_dir, img_file)
    watershed_segmentation(img_path)

print(f"\n Total trees detected across {len(image_files)} images: {total_tree_count}")

# 10. Evaluation (center-based)
def evaluate_center_based(result_dict, ground_truth_dict):
    all_precisions, all_recalls, all_f1s = [], [], []
    for filename in ground_truth_dict:
        gt_boxes = ground_truth_dict.get(filename, [])
        det_boxes = result_dict.get(filename, [])
        matched_gt = set()
        tp = 0
        fp = 0

        for det_box in det_boxes:
            x_center = (det_box[0] + det_box[2]) / 2
            y_center = (det_box[1] + det_box[3]) / 2
            match_found = False
            for i, gt_box in enumerate(gt_boxes):
                if i in matched_gt:
                    continue
                if (gt_box[0] <= x_center <= gt_box[2]) and (gt_box[1] <= y_center <= gt_box[3]):
                    tp += 1
                    matched_gt.add(i)
                    match_found = True
                    break
            if not match_found:
                fp += 1
        fn = len(gt_boxes) - len(matched_gt)
        precision = tp / (tp + fp) if (tp + fp) else 0
        recall = tp / (tp + fn) if (tp + fn) else 0
        f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) else 0
        all_precisions.append(precision)
        all_recalls.append(recall)
        all_f1s.append(f1)

    print("\n CENTER-BASED MATCHING RESULTS:")
    print("Mean Precision:", repr(np.mean(all_precisions)))
    print("Mean Recall:", repr(np.mean(all_recalls)))

# Run evaluation
evaluate_center_based(result_dict, ground_truth)